# Setup
title:        Fefe Hern
tagline:      A Coder, with some interests in baking, music, art and literature.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fernando Hernandez
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
