# Setup
title:        Fefe Hern
tagline:      Software Developer, with some interests in baking, music, art and literature.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fernando Hernandez
  url:        http://yourhomepage.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
